server:
   port: 8886
   servlet:
      session:
        timeout: 6000

hello:
  name: 你好


# swagger开关
swagger:
  enabled:  true
  info:
    basePackage: com.licc.es.controller
    title: 发布控制服务
    desc: 发布控制服务
    termsOfServiceUrl: http://127.0.0.1:${server.port}/
    version: 1.0
    contact:
        name: 发布控制服务
        url: http://127.0.0.1:${server.port}/swagger-ui.html
        email:

spring:
    elasticsearch:
      rest:
        uris: http://47.116.141.109:9200

# 打印日志
logging:
#控制台日志输出级别,这里设置的级别，控制xml文件中console控制台的输出，不设置默认info
  level:
     com.licc.es: trace
#配置日志输出
  config: classpath:log4j2-dev.xml

